(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], pick=a=>a[Math.floor(Math.random()*a.length)];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const era=(title,date,where,roles,items,places,people,notes,atmos,artifacts)=>({title,date,where,roles,items,places,people,notes,atmos,artifacts});
const eras={
 titanic:era('RMS Titanic','April 10–15, 1912','North Atlantic voyage',['Second-class passenger','Steward','Nurse','Wireless assistant','Third-class traveler','Shipboard journalist'],['ticket','coat','small bag','pocket watch'],['Boat Deck','Grand Staircase','Second-Class Library','Promenade','Dining Saloon','Wireless Room'],['steward','fellow traveler','ship officer','musician','wireless operator'],['Class shaped access to spaces and routines aboard the ship.','The voyage began in Southampton on April 10, 1912.'],['cold ocean air and polished brass','quiet engine vibration beneath the deck','salt air, footsteps, and distant music'],['White Star Line luggage tag','menu card','postcard of the ship']),
 west:era('Frontier West','1880s','Silver Creek, fictional western town',['Town reporter','Ranch hand','Deputy','Traveling teacher','Stagecoach passenger','General-store clerk'],['notebook','coins','bandanna','water flask'],['Main Street','Sheriff’s Office','General Store','Livery Stable','Ranch Road','Newspaper Office'],['sheriff','rancher','storekeeper','telegraph operator','stagecoach driver'],['This town is fictional but built from historical frontier patterns.'],['dust hanging in afternoon light','wagon wheels over hard-packed earth','lamp glow from wooden storefronts'],['telegraph blank','trade token','ranch ledger page']),
 egypt:era('Ancient Egypt','c. 1300 BCE','Nile-side settlement',['Scribe apprentice','Market helper','Boat worker','Craftsperson','Temple runner','Merchant assistant'],['reed pen','linen pouch','bread ration','small amulet'],['River Landing','Market Lane','Scribe Workshop','Courtyard Home','Craft Quarter','Temple Approach'],['scribe','boatman','merchant','weaver','potter'],['Daily life depended heavily on the Nile, seasonal work, household labor, and local exchange.'],['river breeze carrying voices from the quay','sun-baked stone and shaded courtyards','market chatter under linen awnings'],['ostracon shard','faience bead','reed stylus']),
 medieval:era('Castle & Village','late Middle Ages','Castle town and surrounding village',['Kitchen helper','Messenger','Village baker','Apprentice','Herbalist helper','Traveling musician'],['cloth purse','bread','wooden cup','wax tablet'],['Castle Gate','Market Square','Bakehouse','Great Hall','Village Lane','Riverside Mill'],['baker','guard','merchant','servant','miller'],['Medieval life varied greatly by region, status, occupation, and century.'],['wood smoke and church bells','muddy lanes after a passing shower','torchlight warming stone walls'],['wax tablet','market tally','small pilgrim badge']),
 victorian:era('Victorian City','1890s','Gaslit industrial city',['Reporter','Shop assistant','Boarding-house resident','Messenger','Theater worker','Clerk'],['notebook','tram fare','umbrella','calling card'],['Railway Station','Market Arcade','Newspaper Office','Theater Row','Boarding House','Public Gardens'],['editor','shopkeeper','cab driver','seamstress','constable'],['Urban life mixed new technologies with sharp class differences.'],['gas lamps flickering in damp air','tram bells and newspaper cries','coal smoke above crowded streets'],['tram ticket','calling card','newspaper clipping']),
 fifties:era('Mid-Century Main Street','1950s','American town center',['Diner server','Record-shop clerk','Student reporter','Movie usher','Office assistant','Neighborhood visitor'],['coins','notepad','bus token','paper bag'],['Diner','Record Shop','Movie House','Department Store','Neighborhood Block','Community Hall'],['waitress','radio host','shop clerk','student','projectionist'],['Experiences in 1950s America differed sharply by race, region, class, and gender.'],['jukebox music through a diner door','chrome, neon, and evening traffic','radio voices drifting from open windows'],['bus token','movie stub','45 rpm sleeve']),
 roaring:era('Roaring Twenties','1920s','Fast-growing American city',['Radio assistant','Department-store clerk','Reporter','Jazz-club server','Office typist','Photographer'],['notebook','streetcar fare','camera plate','gloves'],['Radio Studio','Department Store','Jazz District','Newsroom','Train Terminal','City Park'],['bandleader','reporter','clerk','radio announcer','photographer'],['The decade brought major cultural change alongside inequality and social conflict.'],['brass music spilling onto the street','typewriters clacking in a newsroom','electric signs above crowded sidewalks'],['radio program card','streetcar transfer','dance ticket']),
 apollo:era('Apollo Era','1969','Space-age American city',['Mission support clerk','TV reporter','Engineering assistant','Neighborhood host','Student science reporter','Telephone operator'],['clipboard','press pass','transistor radio','pencil'],['Mission Control Visitor Area','TV Studio','Engineering Office','Neighborhood Watch Party','Science Classroom','Newsstand'],['engineer','reporter','technician','teacher','neighbor'],['Apollo 11 landed humans on the Moon in July 1969.'],['television sets glowing in dark rooms','headsets and clipped technical voices','summer-night excitement around a radio'],['mission patch replica','press bulletin','TV schedule']),
 rome:era('Roman City','2nd century CE','Busy Roman provincial city',['Courier','Market helper','Bath attendant','Scribe','Baker assistant','Visitor'],['coin purse','wax tablet','sandals','water flask'],['Forum','Baths','Bakery','Apartment Street','Temple Precinct','Market Stalls'],['baker','merchant','scribe','bath attendant','courier'],['Roman cities depended on trade, enslaved and free labor, public infrastructure, and local government.'],['stone streets alive with carts and vendors','steam rising from public baths','olive oil and bread from market stalls'],['wax tablet','oil lamp fragment','coin replica']),
 renaissance:era('Renaissance City','1500s','Italian-inspired city-state',['Printer’s apprentice','Artist assistant','Merchant clerk','Messenger','Tailor apprentice','Musician'],['paper folio','coins','ribbon','charcoal stick'],['Piazza','Print Shop','Artist Workshop','Merchant Hall','Tailor Street','Music Court'],['printer','painter','merchant','tailor','musician'],['The Renaissance was not one uniform experience; urban life varied across Europe.'],['bells over a crowded piazza','ink and paper inside a print shop','music echoing from an upper window'],['printed broadside','pigment sample','merchant seal']),
 revolution:era('Revolution-Era City','1776','Atlantic colonial city',['Printer’s helper','Messenger','Shopkeeper','Dock worker','Household servant','Apprentice'],['printed notice','coins','satchel','quill'],['Print Shop','Tavern','Market','Wharf','Meeting Hall','Residential Lane'],['printer','merchant','dock worker','messenger','innkeeper'],['Political loyalties and lived experiences varied widely during the American Revolution.'],['presses thumping behind a shop door','dock ropes creaking at the wharf','public debate rising from a tavern'],['broadside','quill','trade token']),
 homefront:era('Wartime Home Front','1940s','American home-front town',['Factory clerk','Radio listener','Student volunteer','Shop worker','Letter writer','Bus traveler'],['ration book','coins','letter paper','bus pass'],['Factory Gate','Radio Shop','Grocery','USO-style Hall','Neighborhood Block','Movie House'],['factory worker','grocer','radio announcer','student','letter carrier'],['Home-front experiences varied by race, gender, region, military connection, and job.'],['radio bulletins between songs','factory whistles over morning traffic','ration signs in shop windows'],['ration stamp replica','V-mail style sheet','movie ticket']),
 goldrush:era('Gold Rush Country','1849','Booming California settlement',['Prospector','Cook','Merchant clerk','Teamster','Letter writer','Laundry worker'],['tin cup','coins','canvas bag','letter'],['River Claim','Supply Store','Cook Tent','Main Trail','Post Office','Boarding Tent'],['miner','merchant','cook','teamster','postmaster'],['Gold Rush communities were diverse, unstable, expensive, and often dangerous.'],['pickaxes ringing near the river','canvas tents snapping in dry wind','voices bargaining over scarce supplies'],['claim marker','store receipt','postmark replica']),
 depression:era('Depression-Era Main Street','1933','American town during the Great Depression',['Relief-office clerk','Shop helper','Radio listener','Job seeker','Student','Newspaper carrier'],['coins','lunch sack','newspaper','pencil'],['Relief Office','Main Street','Radio Shop','Library','Market','Rail Depot'],['librarian','shopkeeper','job seeker','radio repairer','reporter'],['The Great Depression affected communities differently, but unemployment and hardship were widespread.'],['radio news from an open shop door','quiet storefronts and careful shoppers','train whistles carrying across town'],['relief notice','library card','newspaper clipping']),
 paris1900:era('Paris at the Exposition','1900','Paris during the Exposition Universelle',['Visitor','Poster artist','Café server','Photographer','Pavilion guide','Reporter'],['metro ticket','guidebook','coins','postcard'],['Exposition Pavilion','Café','Boulevard','Metro Entrance','Poster Studio','Riverbank'],['guide','artist','server','photographer','visitor'],['The 1900 exposition showcased technology, empire, art, and mass entertainment.'],['electric lights turning evening streets bright','café conversation under striped awnings','crowds moving between exhibition halls'],['exposition ticket','metro stub','art nouveau postcard']),
 sail:era('Age of Sail Harbor','1720s','Atlantic port town',['Dock clerk','Sailmaker apprentice','Cook','Merchant helper','Harbor messenger','Traveler'],['rope knife','coin pouch','manifest scrap','tin cup'],['Wharf','Ropewalk','Warehouse','Tavern','Ship Chandler','Harbor Office'],['sailor','merchant','sailmaker','dock clerk','innkeeper'],['Ports connected global trade while also reflecting colonialism, forced labor, and dangerous maritime work.'],['tar, rope, and salt air','rigging tapping against tall masts','cargo calls echoing across the quay'],['cargo tally','rope sample','port token']),
 pompeii:era('Pompeii Before the Eruption','79 CE','Pompeii, Roman Italy',['Bakery helper','Household runner','Market shopper','Bath attendant','Craft worker','Visitor'],['coin','bread basket','oil flask','sandals'],['Forum','Bakery','Baths','House Courtyard','Workshop Street','City Gate'],['baker','merchant','household servant','craft worker','traveler'],['Pompeii preserves unusually detailed evidence of Roman urban life.'],['bread ovens warming a narrow street','fountain water splashing into a basin','voices bouncing off painted walls'],['graffiti rubbing','bread-stamp replica','small lamp']),
 viking:era('Viking Harbor','c. 900','Northern trading harbor',['Trader','Boat repairer','Farm visitor','Craft apprentice','Storyteller','Messenger'],['wool pouch','comb','knife sheath','trade weight'],['Jetty','Longhouse','Craft Yard','Market','Farm Track','Boat Shed'],['trader','smith','farmer','boatbuilder','storyteller'],['Viking-age communities traded widely and included farmers, craftspeople, merchants, raiders, and enslaved people.'],['cold wind snapping over the jetty','hammering from a craft yard','smoke curling from longhouse roofs'],['trade weight','bone comb','bead']),
 silkroad:era('Silk Road Oasis','c. 800','Central Asian oasis town',['Caravan assistant','Translator','Guesthouse helper','Merchant','Cook','Animal handler'],['water skin','cloth purse','travel token','small ledger'],['Caravan Yard','Market','Guesthouse','Tea Stall','Stable','City Gate'],['merchant','translator','cook','camel handler','traveler'],['The Silk Roads were networks of routes, not one single road, and moved ideas as well as goods.'],['bells from pack animals at the gate','spices and dust in the market air','many languages overlapping in the courtyard'],['trade seal','cloth sample','caravan tally']),
 edwardian:era('Edwardian Seaside','1908','British seaside resort',['Postcard seller','Tea-room server','Holiday visitor','Pier attendant','Photographer','Shop clerk'],['pennies','postcard','hat pin','tram ticket'],['Pier','Tea Room','Promenade','Photo Studio','Bandstand','Bathing Area'],['photographer','musician','server','visitor','shopkeeper'],['Seaside resorts mixed leisure, class display, new transport, and mass tourism.'],['brass band music across the promenade','gulls above the pier','tea cups clinking in a crowded room'],['postcard','pier ticket','photo-card'])
};
const modes={roleplay:'ROLE-PLAY',explore:'FREE EXPLORE',mystery:'MYSTERY',story:'STORY',games:'GAMES',daily:'DAILY LIFE',newspaper:'HEADLINES',cozy:'JUST VISIT'};
let state={era:'titanic',mode:'roleplay',score:0,questions:0,storyStep:0,caseStep:0,routeStep:0,daypart:0,thread:[],lastChoice:'',persona:null};
const dayparts=['morning','afternoon','evening','night'];
function toast(msg){let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.append(t)}t.textContent=msg;clearTimeout(t._x);t._x=setTimeout(()=>t.remove(),2200)}
function getEra(){return eras[state.era]||eras.titanic}
function saveVisits(){const v=store.get('htp_visits',[]);if(!v.includes(state.era)){v.push(state.era);store.set('htp_visits',v)}renderPassport()}
function sceneFor(mode,e=getEra()){
 const p=pick(e.places), person=pick(e.people), atm=pick(e.atmos), role=state.persona?.role||pick(e.roles);
 const map={
 roleplay:`You are a ${role}. ${atm}. Near ${p}, a ${person} pauses long enough to notice you. You have enough freedom to follow the day wherever it leads.`,
 explore:`No mission today. You wander toward ${p}. ${atm}. You can watch, listen, enter a public space, or strike up a conversation with a ${person}.`,
 mystery:`A harmless problem has surfaced near ${p}: an important item is missing and three people remember the morning differently. A ${person} may know more than they first say.`,
 story:`Your day starts normally near ${p}, until a small interruption changes your plans. ${atm}. Someone asks for your help before the opportunity disappears.`,
 games:`The Timekeeper opens a challenge table based on ${e.title}. Pick a game below, or keep exploring and return later.`,
 daily:`Spend time around ${p} learning what ordinary work, meals, errands, entertainment, and social expectations feel like here.`,
 newspaper:`A fresh edition has arrived. Headlines cover transport, prices, public events, local gossip, and the wider world as people here would encounter it.`,
 cozy:`Nothing urgent is happening. ${atm}. You can sit, browse, eat, listen, people-watch, or slowly walk through ${p} with no task to finish.`
 };
 return map[mode]||map.roleplay;
}
function renderChoices(){const e=getEra();const p=pick(e.places), person=pick(e.people);const opts=state.mode==='cozy'?[`Sit somewhere comfortable`,`Browse ${p}`,`Get something to eat`,`People-watch quietly`]:state.mode==='mystery'?[`Examine the area around ${p}`,`Question the ${person}`,`Check the timeline`,`Follow a small inconsistency`]:[`Go to ${p}`,`Talk to the ${person}`,`Look around carefully`,`Do something unexpected`];$('#choices').innerHTML=opts.map(x=>`<button class="choice-btn">${x}</button>`).join('');$$('.choice-btn').forEach(b=>b.onclick=()=>doChoice(b.textContent))}
function renderEra(newScene=true){const e=getEra();document.body.dataset.era=state.era;$('#experienceTitle').textContent=e.title;$('#where').textContent=e.where;$('#date').textContent=e.date;$('#role').textContent=state.persona?.role||pick(e.roles);$('#items').textContent=e.items.join(' • ');$('#modeBadge').textContent=`${modes[state.mode]} MODE`;if(newScene)$('#sceneText').textContent=sceneFor(state.mode,e);$('#historyNote').textContent=`History note: ${pick(e.notes)}`;$('#atmosphereText').textContent=pick(e.atmos);$('#journeyStatus').textContent=state.thread.length?`${state.thread.length} connected moment${state.thread.length===1?'':'s'} in this visit.`:'No continuing thread yet.';renderChoices();renderDistricts();renderCharacters();renderPersonaRoles();renderDeck();saveVisits()}
function doChoice(txt){const e=getEra();state.lastChoice=txt;state.thread.push({era:state.era,mode:state.mode,text:txt});const next=`You choose to ${txt.charAt(0).toLowerCase()+txt.slice(1)}. ${pick(e.atmos)}. A ${pick(e.people)} reacts, and the scene shifts toward ${pick(e.places)}. ${state.mode==='mystery'?'You notice one detail that does not quite match the first account.':'You now have another direction you can follow.'}`;$('#sceneText').textContent=next;$('#journeyStatus').textContent=`${state.thread.length} connected moments in this visit.`;renderChoices();store.set('htp_thread',state.thread)}
function openEra(key){state.era=eras[key]?key:'titanic';document.body.dataset.era=state.era;state.persona=store.get(`htp_persona_${state.era}`,null);store.set('htp_last_era',state.era);state.storyStep=0;state.caseStep=0;state.routeStep=0;renderEra();renderWallet();$('#experiencePanel').scrollIntoView({behavior:'smooth',block:'start'})}
function setMode(m){state.mode=m;store.set('htp_last_mode',m);$$('.mode-card').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));renderEra()}
function renderDistricts(){const e=getEra();$('#districtGrid').innerHTML=e.places.map(p=>`<div class="district-card"><b>📍 ${p}</b><p>Open this area and let the current mode shape what happens there.</p><button data-place="${p.replaceAll('"','&quot;')}">Enter</button></div>`).join('');$$('[data-place]').forEach(b=>b.onclick=()=>{$('#sceneText').textContent=`You head into ${b.dataset.place}. ${pick(e.atmos)}. ${sceneFor(state.mode,e)}`;state.thread.push({place:b.dataset.place});$('#journeyStatus').textContent=`${state.thread.length} connected moments in this visit.`})}
function renderCharacters(){const e=getEra(),rel=store.get('htp_rel',{}),cur=rel[state.era]||{};$('#characterGrid').innerHTML=e.people.map((p,i)=>{const n=cur[p]||0,level=n>=5?'Friend':n>=3?'Familiar face':n>=1?'Acquaintance':'Stranger';return `<div class="character-card"><b>👤 ${p[0].toUpperCase()+p.slice(1)}</b><span class="relationship-level">${level} • ${n} conversation${n===1?'':'s'}</span><p>${pick(['Looks busy but approachable.','Seems to know the neighborhood well.','Has been watching the day unfold.','Might have a story, errand, rumor, or useful detail.'])}</p><div class="character-actions"><button data-person="${i}" data-talk="news">Local news</button><button data-person="${i}" data-talk="work">Ask about work</button><button data-person="${i}" data-talk="social">Spend time together</button><button data-person="${i}" data-talk="favor">Ask a favor</button></div></div>`}).join('');$$('[data-person]').forEach(b=>b.onclick=()=>talkToPerson(+b.dataset.person,b.dataset.talk))}
function talkToPerson(i,kind){const e=getEra(),p=e.people[i],rel=store.get('htp_rel',{});rel[state.era]=rel[state.era]||{};const before=rel[state.era][p]||0;const replies={news:`The ${p} lowers their voice and tells you what people are talking about near ${pick(e.places)}: ${pick(['a public event later today','a delivery that arrived late','someone new in town','a price that suddenly changed','weather that may affect tomorrow'])}.`,work:`The ${p} explains the rhythm of the job—when the day starts, what tools matter, who gives orders, and what part of the work people rarely notice.`,social:before>=2?`The ${p} recognizes you now. You spend a relaxed stretch of time together near ${pick(e.places)}, trading ordinary stories instead of chasing a mission.`:`You spend a little time with the ${p}. The conversation stays polite at first, then becomes easier as you talk about the day.`,favor:before>=2?`Because you are becoming familiar, the ${p} agrees to help. They point you toward ${pick(e.places)} and give you a useful introduction.`:`The ${p} is cautious. They suggest you talk a little longer before asking for anything important.`};$('#sceneText').textContent=replies[kind]||replies.news;rel[state.era][p]=before+1;store.set('htp_rel',rel);renderRelations();renderCharacters();state.thread.push(`${p}: ${kind}`);store.set('htp_thread',state.thread);$('#journeyStatus').textContent=`${state.thread.length} connected moments in this visit.`}

function event(){const e=getEra();const type=pick(['festival','quiet day','mystery','arrival','weather shift','market rush','evening gathering']);$('#eventTitle').textContent=`${e.title}: ${type.replace(/\b\w/g,c=>c.toUpperCase())}`;$('#eventText').textContent=`Around ${pick(e.places)}, ${pick(['people are preparing for something unusual','a crowd is slowly forming','a small problem has everyone comparing stories','the pace of the day has suddenly changed','locals are taking advantage of a rare quiet spell'])}. You can enter it, ignore it, or simply watch.`}
function randomAdventure(){const keys=Object.keys(eras).filter(k=>k!==state.era);state.era=pick(keys);state.mode=pick(Object.keys(modes));state.thread=[];renderEra();$('#randomResult').textContent=`Destination: ${getEra().title} • Mode: ${modes[state.mode]} • Role: ${$('#role').textContent} • Opening: ${$('#sceneText').textContent}`}
function renderPassport(){const v=store.get('htp_visits',[]);$('#passportStamps').innerHTML=v.length?v.map(k=>`<span class="stamp">⏳ ${eras[k]?.title||k}</span>`).join(''):'<span class="stamp">No stamps yet.</span>'}
function renderPersonaRoles(){const e=getEra();$('#personaRole').innerHTML=e.roles.map(r=>`<option>${r}</option>`).join('')}
function savePersona(){state.persona={name:$('#personaName').value.trim()||'Unnamed traveler',role:$('#personaRole').value,trait:$('#personaTrait').value,goal:$('#personaGoal').value};store.set(`htp_persona_${state.era}`,state.persona);$('#personaResult').textContent=`Saved: ${state.persona.name} — ${state.persona.trait} ${state.persona.role}. Goal: ${state.persona.goal}.`;renderEra(false)}
function loadPersona(){state.persona=store.get(`htp_persona_${state.era}`,null);$('#personaResult').textContent=state.persona?`Loaded ${state.persona.name}, ${state.persona.role}.`:'No saved character for this era yet.';renderEra(false)}
function rerollPersona(){const e=getEra();$('#personaName').value=pick(['Clara','Samuel','Mara','Thomas','Nell','James','Ada','Elias']);$('#personaRole').value=pick(e.roles);$('#personaTrait').value=pick([...$('#personaTrait').options].map(o=>o.value));$('#personaGoal').value=pick([...$('#personaGoal').options].map(o=>o.value));savePersona()}
const lifeMap={home:['rooms','chores','family expectations','privacy','sleeping arrangements'],food:['markets','meals','ingredients','prices','table customs'],work:['tools','hours','training','pay','status'],fun:['music','games','public entertainment','celebrations','gossip'],customs:['manners','beliefs','holidays','social expectations','unwritten rules'],travel:['roads','walking','ships','carts','trains','journey times']};
function life(type){const e=getEra(), topic=pick(lifeMap[type]);$('#lifeResult').textContent=`${e.title} — ${type.toUpperCase()}: You spend time near ${pick(e.places)} focusing on ${topic}. ${pick(e.atmos)}. A ${pick(e.people)} explains how this part of ordinary life shapes the day.`}
let currentCase=null;function newCase(){const e=getEra();currentCase={title:pick(['The Misplaced Parcel','The Mixed-Up Message','The Missing Ledger','The Wrong Delivery','The Vanished Keepsake']),clues:[],witnesses:0};$('#caseTitle').textContent=currentCase.title;$('#caseNarrative').textContent=`Near ${pick(e.places)}, something important has gone missing. Nobody appears dangerous, but several accounts disagree. Your job is to reconstruct what happened.`;$('#caseEvidence').innerHTML=''}
function addClue(){if(!currentCase)newCase();const e=getEra();const c=pick(['a time written in the margin','mud or dust where it should not be','a receipt with a different destination','someone remembers hearing a bell','an object was moved before anyone noticed','a second person saw the same visitor']);currentCase.clues.push(c);$('#caseEvidence').insertAdjacentHTML('beforeend',`<span class="evidence-chip">🔎 ${c}</span>`)}
function witness(){if(!currentCase)newCase();currentCase.witnesses++;const e=getEra();$('#caseNarrative').textContent=`Witness ${currentCase.witnesses}: the ${pick(e.people)} remembers ${pick(['seeing someone hurry away','a delivery arriving earlier than expected','hearing two people argue about directions','an item being placed on the wrong counter','nothing unusual until much later'])}.`}
function solve(){if(!currentCase)newCase();$('#caseNarrative').textContent=currentCase.clues.length<2?'You can make a guess now, but the Timekeeper suggests examining at least two clues first.':`Your conclusion: the evidence points to confusion, timing, and a mistaken handoff rather than a dramatic crime. Case closed with ${currentCase.clues.length} clues and ${currentCase.witnesses} witness account(s).`;if(currentCase.clues.length>=2){const q=store.get('htp_quests',0)+1;store.set('htp_quests',q);renderQuests()}}
const historyQuestions={
 titanic:[['Which port did Titanic leave on April 10, 1912?','Southampton',['Liverpool','Belfast']],['What struck Titanic on April 14, 1912?','An iceberg',['A reef','Another ship']]],
 west:[['Which transport linked many growing western towns?','Railroads',['Jet aircraft','Subways']],['Which was a common source of ranch income?','Cattle',['Microchips','Automobiles']]],
 egypt:[['Which river supported ancient Egyptian agriculture?','The Nile',['The Thames','The Rhine']]],
 medieval:[['Which worker commonly made bread for villagers?','A baker',['A telegraph operator','A film director']]],
 victorian:[['Which fuel illuminated many Victorian city streets?','Coal gas',['Solar batteries','Jet fuel']]],
 fifties:[['Which format was popular for playing recorded music?','Vinyl records',['Compact discs','Streaming apps']]],
 roaring:[['Which medium brought live entertainment into many homes?','Radio',['Television streaming','Podcasts']]],
 apollo:[['In what year did Apollo 11 land on the Moon?','1969',['1959','1979']]],
 rome:[['Which public space served trade and civic life in Roman cities?','Forum',['Airport terminal','Cinema']]],
 renaissance:[['Which technology helped spread books in Renaissance Europe?','Printing press',['Television','Typewriter']]],
 revolution:[['In what year was the U.S. Declaration of Independence adopted?','1776',['1812','1492']]],
 homefront:[['What was often used to manage scarce food and goods during WWII?','Ration books',['Credit cards','Online coupons']]],
 goldrush:[['Which metal drew many people to California in 1849?','Gold',['Tin','Aluminum']]],
 depression:[['Which decade includes the Great Depression?','1930s',['1830s','1960s']]],
 paris1900:[['What major exposition took place in Paris in 1900?','Exposition Universelle',['Expo 1967','Great Exhibition of 1851']]],
 sail:[['What helped sailing ships move across the ocean?','Wind',['Diesel turbines','Jet engines']]],
 pompeii:[['Which volcano erupted near Pompeii in 79 CE?','Mount Vesuvius',['Mount Etna','Mount Fuji']]],
 viking:[['What kind of vessel often supported Viking-era travel and trade?','Longship',['Steam locomotive','Submarine']]],
 silkroad:[['What was the Silk Road?','A network of trade routes',['One single paved road','A Roman aqueduct']]],
 edwardian:[['What did holiday visitors commonly send from seaside resorts?','Postcards',['Emails','Video calls']]]
};
let gameLocked=false;
function playGame(type){
 const e=getEra();let q,a,wrong;
 if(type==='fact'){[q,a,wrong]=pick(historyQuestions[state.era]||historyQuestions.titanic)}
 else if(type==='timeline'){
   const before=['egypt','rome','pompeii','viking','silkroad','medieval','renaissance','sail','revolution','goldrush','west','victorian'];
   q=`Does this portal’s time period come before or after the year 1900?`;
   a=before.includes(state.era)?'Before 1900':state.era==='paris1900'?'The year 1900':'After 1900';wrong=['Before 1900','The year 1900','After 1900'].filter(x=>x!==a)
 }else if(type==='artifact'){
   a=pick(e.artifacts);q=`Which object could your character have in ${e.title}?`;
   const pool=['smartphone','plastic credit card','digital wristwatch','wireless earbuds','electric scooter','modern laptop'];wrong=pool.filter(x=>!e.artifacts.includes(x)).sort(()=>Math.random()-.5).slice(0,2);
 }else{
   a=pick(e.people);q=`Which person might you meet in ${e.title}?`;
   wrong=['airline pilot','software engineer','streaming influencer','modern game designer'].filter(x=>!e.people.includes(x)).sort(()=>Math.random()-.5).slice(0,2)
 }
 const answers=[a,...wrong.slice(0,2)].sort(()=>Math.random()-.5);gameLocked=false;
 $('#gamePanel').innerHTML=`<b>${esc(q)}</b><div class="choices" id="gameAnswers">${answers.map(x=>`<button class="answer-btn">${esc(x)}</button>`).join('')}</div><p id="gameFeedback" role="status" aria-live="polite"></p>`;
 $$('.answer-btn').forEach(b=>b.onclick=()=>{if(gameLocked)return;gameLocked=true;state.questions++;const ok=b.textContent===a;if(ok)state.score++;$('#score').textContent=state.score;$('#questions').textContent=state.questions;$('#gameFeedback').textContent=ok?'Correct!':`The answer is: ${a}`;$$('.answer-btn').forEach(x=>{x.disabled=true;if(x.textContent===a)x.classList.add('correct-answer')})});
}
function mini(type){const e=getEra();const m={artifact:`On the artifact table: ${pick(e.artifacts)}. Inspect its material, wear, markings, and likely everyday use.`,meal:`A local meal is being served near ${pick(e.places)}. Ask what ingredients were common, what was expensive, and who prepared the food.`,gossip:`Rumor: a ${pick(e.people)} says something unusual happened near ${pick(e.places)}. You can investigate or dismiss it as gossip.`,shop:`You enter ${pick(e.places)} with a small budget and compare what people buy for necessity versus status.`,job:`You spend part of the day assisting a ${pick(e.people)} and learning the rhythm, tools, and expectations of the work.`,night:`Night falls. ${pick(e.atmos)}. Public spaces change, some work continues, and other activities begin.`,music:`Listen to the social atmosphere of ${e.title}: where people gather, what entertainment costs, and who gets access.`,postcard:`Postcard draft: “Today I visited ${pick(e.places)}. ${pick(e.atmos)}. The strangest thing I noticed was how different ordinary routines feel here.”`,wardrobe:`Your ${$('#role').textContent||pick(e.roles)} clothing is shaped by work, status, weather, local custom, and what you can afford.`};$('#miniResult').textContent=m[type]}
function titanic(ch){const t={boarding:'Southampton, April 10, 1912. You board among luggage, porters, families, and crew. Explore first impressions before departure.',ship:'The voyage settles into routine: meals, promenade, work shifts, reading rooms, music, class differences, and shipboard schedules.',signals:'Wireless traffic and ice messages become part of the background. This chapter focuses on communication, weather, navigation, and what different people knew.',collision:'Late April 14. The ship strikes an iceberg. There is no score here: the focus is information, uncertainty, movement through the ship, and crew response.',boats:'Evacuation unfolds unevenly. This chapter focuses on locations, instructions, class and access, lifeboat loading, and confusion without turning survival into a game.',aftermath:'The sinking is followed through survivor accounts, inquiries, headlines, memorials, and changes to maritime safety.'};state.era='titanic';$('#titanicChapterResult').textContent=t[ch];renderEra(false)}
function renderDeck(){const e=getEra();const cards=[['Social',`Meet a ${pick(e.people)} near ${pick(e.places)}.`],['Mystery',`Follow a harmless clue through ${pick(e.places)}.`],['Quiet',`Spend an unhurried hour at ${pick(e.places)}.`],['Work',`Assist a ${pick(e.people)} for part of the day.`],['Explore',`Walk from ${pick(e.places)} to ${pick(e.places)}.`]];$('#adventureCards').innerHTML=cards.sort(()=>Math.random()-.5).slice(0,3).map(([a,b])=>`<div class="adventure-card"><b>${a}</b><p>${b}</p><button data-adv="${b.replaceAll('"','&quot;')}">Start</button></div>`).join('');$$('[data-adv]').forEach(b=>b.onclick=()=>doChoice(b.dataset.adv))}
function storyStart(){state.storyStep=1;$('#storyChapter').textContent='Scene 1 of 5';$('#storyMeter').style.width='20%';$('#storyOutput').textContent=`Opening: ${sceneFor('story')}`}
function storyNext(branch=false){if(!state.storyStep)return storyStart();state.storyStep=Math.min(5,state.storyStep+1);const e=getEra();$('#storyChapter').textContent=`Scene ${state.storyStep} of 5`;$('#storyMeter').style.width=`${state.storyStep*20}%`;$('#storyOutput').textContent=`${branch?'Alternate path: ':'Next scene: '}You move toward ${pick(e.places)}. ${pick(e.atmos)}. A ${pick(e.people)} changes what you thought the day would become.`}
function storyEnd(){if(state.storyStep){const m=store.get('htp_memories',[]);m.push({era:getEra().title,scene:$('#storyOutput').textContent});store.set('htp_memories',m);renderMemories()}state.storyStep=0;$('#storyChapter').textContent='Episode closed.';$('#storyMeter').style.width='0';$('#storyOutput').textContent='Your episode is saved as a memory of this visit. Start another whenever you want.'}
function buildRoute(){const e=getEra(), ps=[...e.places].sort(()=>Math.random()-.5).slice(0,3);state.route=ps;state.routeStep=0;$('#routeStops').innerHTML=ps.map((p,i)=>`<div class="route-stop"><b>${i+1}. ${p}</b><p>${['Morning stop','Midday stop','Evening stop'][i]}</p></div>`).join('')}
function walkRoute(){if(!state.route?.length)buildRoute();const p=state.route[state.routeStep%state.route.length];state.routeStep++;$('#sceneText').textContent=`Route stop ${state.routeStep}: ${p}. ${sceneFor(state.mode)}`;$('#experiencePanel').scrollIntoView({behavior:'smooth'})}
function renderJournal(){const j=store.get('htp_journal',[]);$('#journalEntries').innerHTML=j.slice().reverse().map(x=>`<div class="memory-card"><b>${esc(x.era)}</b><p>${esc(x.text)}</p></div>`).join('')}
function renderCollections(){const arts=store.get('htp_artifacts',[]);$('#artifactCabinet').innerHTML=arts.map(a=>`<span class="stamp">🧳 ${esc(a)}</span>`).join('')||'<span class="stamp">No artifacts yet.</span>';const fav=store.get('htp_favs',[]);$('#favoritePortals').innerHTML=fav.map(k=>`<button data-fav="${k}">⭐ ${eras[k]?.title||'Unknown portal'}</button>`).join('');$$('[data-fav]').forEach(b=>b.onclick=()=>openEra(b.dataset.fav))}
function renderQuests(){const e=getEra(), done=store.get('htp_quests',0);$('#questCount').textContent=done;const qs=[`Talk to someone in ${e.title}`,`Visit two different places`,`Save a journal memory`,`Solve a harmless case`];$('#questGrid').innerHTML=qs.map(q=>`<div class="quest-card"><b>Optional Quest</b><p>${q}</p><button class="quest-done">Mark Complete</button></div>`).join('');$$('.quest-done').forEach(b=>b.onclick=()=>{const n=store.get('htp_quests',0)+1;store.set('htp_quests',n);b.textContent='✓ Complete';b.disabled=true;renderAchievements();$('#questCount').textContent=n})}
function renderAchievements(){const visits=store.get('htp_visits',[]).length, arts=store.get('htp_artifacts',[]).length,j=store.get('htp_journal',[]).length,q=store.get('htp_quests',0);const a=[['First Jump',visits>=1],['Era Hopper',visits>=5],['Century Collector',visits>=12],['Artifact Keeper',arts>=3],['Journalist',j>=3],['Guild Regular',q>=5]];$('#achievementGrid').innerHTML=a.map(([n,ok])=>`<div class="achievement ${ok?'':'locked'}"><b>${ok?'🏅':'🔒'} ${n}</b></div>`).join('')}
function renderRelations(){const r=store.get('htp_rel',{}), cur=r[state.era]||{};$('#relationshipBook').innerHTML=Object.keys(cur).length?Object.entries(cur).map(([p,n])=>`<span class="stamp">👤 ${esc(p)} • ${n} conversation${n===1?'':'s'}</span>`).join(''):'<span class="stamp">No familiar faces here yet.</span>'}
function renderMemories(){const m=store.get('htp_memories',[]);$('#memoryChest').innerHTML=m.slice().reverse().map(x=>`<div class="memory-card"><b>${esc(x.era)}</b><p>${esc(x.scene)}</p></div>`).join('')||'<span class="stamp">No saved moments yet.</span>'}
function planDay(){const e=getEra(), ps=[...e.places].sort(()=>Math.random()-.5).slice(0,3);$('#dayPlan').innerHTML=`<b>Morning:</b> ${ps[0]}<br><b>Afternoon:</b> ${ps[1]}<br><b>Evening:</b> ${ps[2]}<br><span>${pick(e.atmos)}.</span>`}
function mixVisit(){const keys=Object.keys(eras);state.era=pick(keys);state.mode=pick(Object.keys(modes));renderEra();const e=getEra();$('#visitMixerResult').innerHTML=`<b>${e.title}</b><br>${modes[state.mode]} • ${$('#role').textContent}<br>Start at ${pick(e.places)}, meet a ${pick(e.people)}, try ${pick(['a local meal','a small mystery','a quiet walk','a work shift','a social event'])}, and end the day near ${pick(e.places)}.`}
function atmosphereAdvance(){state.daypart=(state.daypart+1)%4;const e=getEra();$('#atmosphereText').textContent=`${dayparts[state.daypart]} — ${pick(e.atmos)}`}
function continueDay(){const e=getEra();doChoice(`continue through the ${dayparts[state.daypart]} toward ${pick(e.places)}`)}
function freshThread(){state.thread=[];store.set('htp_thread',[]);$('#journeyStatus').textContent='Fresh thread started. Nothing from the previous scene is required.';renderEra()}

let chronicle={step:0,path:[],opening:''};
function renderChronicleLibrary(){const c=store.get('htp_chronicles',[]);const el=$('#chronicleLibrary');if(!el)return;el.innerHTML=c.length?c.slice().reverse().map(x=>`<div class="memory-card"><b>${esc(x.era)}</b><p>${esc(x.text)}</p></div>`).join(''):'<span class="stamp">No saved chronicles yet.</span>'}
function chronicleScene(){const e=getEra();const steps=[
  `Morning begins near ${pick(e.places)}. ${pick(e.atmos)}. A ${pick(e.people)} gives you two ways to spend the first hour.`,
  `By midday, your earlier choice has changed who recognizes you. Someone from ${pick(e.places)} approaches with news that connects to what you did before.`,
  `Evening settles over ${pick(e.places)}. Your path has created one final choice: end quietly, follow one last lead, or spend time with someone you met.`
];return steps[Math.min(chronicle.step,2)]}
function chronicleStart(){chronicle={step:0,path:[],opening:getEra().title};$('#chronicleOutput').textContent=chronicleScene();renderChronicleChoices()}
function renderChronicleChoices(){const e=getEra();const sets=[[`Follow the ${pick(e.people)}`,`Explore ${pick(e.places)}`,`Keep the morning quiet`],[`Ask what changed`,`Check the place yourself`,`Meet someone new`],[`End with a calm meal`,`Follow one last clue`,`Write down what you learned`]];const choices=sets[Math.min(chronicle.step,2)];$('#chronicleChoices').innerHTML=choices.map(x=>`<button class="chronicle-choice">${x}</button>`).join('');$$('.chronicle-choice').forEach(b=>b.onclick=()=>{chronicle.path.push(b.textContent);$('#chronicleOutput').textContent+=`\n\nYou choose: ${b.textContent}.`;$$('.chronicle-choice').forEach(x=>x.disabled=true)})}
function chronicleNext(){if(!chronicle.opening)return chronicleStart();if(!chronicle.path.length||chronicle.path.length<=chronicle.step){toast('Choose a path first.');return}chronicle.step++;if(chronicle.step>2){$('#chronicleOutput').textContent=`Chronicle complete. ${getEra().title}: ${chronicle.path.join(' → ')}.`;$('#chronicleChoices').innerHTML='';return}$('#chronicleOutput').textContent=chronicleScene();renderChronicleChoices()}
function chronicleSave(){if(!chronicle.path.length)return toast('Start a chronicle first.');const c=store.get('htp_chronicles',[]);c.push({era:getEra().title,text:chronicle.path.join(' → ')});store.set('htp_chronicles',c);renderChronicleLibrary();toast('Chronicle saved.')}
function renderNotices(){const n=store.get('htp_notices',[]),el=$('#noticeGrid');if(!el)return;el.innerHTML=n.length?n.slice(-18).map(x=>`<span class="stamp">${esc(x)}</span>`).join(''):'<span class="stamp">Nothing collected yet.</span>'}
function noticeSomething(){const e=getEra();const pool=[`👂 Sound: ${pick(e.atmos)}`,`🧳 Object: ${pick(e.artifacts)}`,`👤 Person: ${pick(e.people)}`,`📍 Place: ${pick(e.places)}`,`🧰 Work: ${pick(e.roles)}`,`🕯️ Custom: an ordinary routine shaped by time, status, and local expectations`];const n=store.get('htp_notices',[]);n.push(`${e.title} — ${pick(pool)}`);store.set('htp_notices',n);renderNotices()}


const localCulture={
 titanic:{food:['tea with bread and cold meats','a formal dining service','a simpler passenger meal'],shop:['postcards','toiletries','small travel necessities'],fun:['shipboard music','reading-room conversation','promenade watching'],event:['a scheduled meal','a deck stroll','an evening gathering']},
 west:{food:['stew with bread','beans and coffee','a boarding-house supper'],shop:['work gloves','canned goods','lamp oil'],fun:['card games','fiddle music','a town social'],event:['mail arrival','a cattle shipment','a Saturday gathering']},
 egypt:{food:['bread with dates','lentils and onions','fish from the river'],shop:['linen','pottery','small amulets'],fun:['music and storytelling','riverbank conversation','festival preparations'],event:['market day','a temple procession','a river delivery']},
 medieval:{food:['pottage and bread','cheese with ale','a market pie'],shop:['candles','cloth','wooden utensils'],fun:['storytelling','music in an inn','market-day games'],event:['saint day preparations','market day','a guild gathering']},
 victorian:{food:['tea and bread','meat pie','a boarding-house supper'],shop:['ribbons','soap','newspapers'],fun:['music hall','public gardens','theater row'],event:['a matinee','a public lecture','a market rush']},
 fifties:{food:['diner sandwich','milkshake and fries','home-style supper'],shop:['records','magazines','department-store goods'],fun:['movie night','record listening','community dance'],event:['school game','movie premiere','community social']},
 roaring:{food:['café lunch','soda-fountain snack','late supper'],shop:['fashion accessories','records','newspapers'],fun:['jazz set','radio show','dance hall'],event:['dance night','radio broadcast','department-store event']},
 apollo:{food:['coffee and sandwiches','TV-dinner style meal','late-night snacks'],shop:['science magazines','souvenir buttons','newspapers'],fun:['watch party','science club','television coverage'],event:['mission update','press briefing','neighborhood watch party']},
 rome:{food:['bread and olives','stew from a food stall','fruit and cheese'],shop:['oil lamps','cloth','spices'],fun:['bathhouse conversation','street performers','public games'],event:['market day','public announcement','festival preparations']},
 renaissance:{food:['bread with cheese','market stew','fruit and wine'],shop:['printed sheets','ribbon','small art goods'],fun:['music court','street performers','public procession'],event:['guild meeting','religious festival','market fair']},
 revolution:{food:['bread and stew','tavern meal','tea substitute and pastry'],shop:['printed broadsides','cloth','household goods'],fun:['tavern debate','public reading','music gathering'],event:['town meeting','news arrival','market day']},
 homefront:{food:['ration-conscious supper','diner lunch','home-baked snack'],shop:['rationed groceries','stationery','movie tickets'],fun:['radio program','movie night','dance hall'],event:['bond drive','community collection','USO-style social']},
 goldrush:{food:['beans and bread','camp stew','expensive fresh meal'],shop:['boots','tools','mail supplies'],fun:['storytelling','music at camp','gambling tables'],event:['mail day','supply wagon arrival','claim news']},
 depression:{food:['simple soup and bread','inexpensive lunch counter meal','home-cooked beans'],shop:['used clothing','newspapers','small household goods'],fun:['radio listening','library visit','community music'],event:['relief notice','job posting','community gathering']},
 paris1900:{food:['café bread and coffee','pastry','restaurant meal'],shop:['postcards','posters','souvenirs'],fun:['exposition pavilion','café music','street performance'],event:['exhibition demonstration','evening illumination','public concert']},
 sail:{food:['salted meat and bread','harbor stew','ale and cheese'],shop:['rope','cloth','ship supplies'],fun:['tavern stories','dockside music','dice games'],event:['ship arrival','cargo auction','tide change']},
 pompeii:{food:['bread and olives','street-food stew','fruit and cheese'],shop:['oil lamps','bread loaves','small household goods'],fun:['bathhouse socializing','street games','public performance'],event:['market rush','bathhouse gathering','local religious observance']},
 viking:{food:['fish and bread','porridge','roasted meat at a feast'],shop:['iron tools','wool','beads'],fun:['storytelling','board games','feast music'],event:['ship return','trading day','hall feast']},
 silkroad:{food:['flatbread and stew','dried fruit and nuts','tea-like hot drink'],shop:['textiles','spices','small metal goods'],fun:['traveler stories','music at an inn','market watching'],event:['caravan arrival','trade negotiation','guest-house gathering']},
 edwardian:{food:['tea and cake','fish supper','seaside snack'],shop:['postcards','ribbons','holiday souvenirs'],fun:['pier show','band concert','boardwalk game'],event:['promenade concert','holiday crowd','pier performance']}
};
function culture(){return localCulture[state.era]||{food:['a local meal'],shop:['ordinary goods'],fun:['a public entertainment'],event:['a community gathering']}}

function walletGet(){return store.get(`htp_wallet_${state.era}`,12)}
function walletSet(v){store.set(`htp_wallet_${state.era}`,Math.max(0,v));if($('#walletCount'))$('#walletCount').textContent=Math.max(0,v)}
function renderWallet(){if($('#walletCount'))$('#walletCount').textContent=walletGet()}
function townLife(type){const e=getEra(),out=$('#townLifeResult'),actions=$('#townLifeActions');actions.innerHTML='';const c=culture();const social=`You join a small social circle near ${pick(e.places)}. A ${pick(e.people)} makes introductions, somebody trades a harmless bit of gossip, and the conversation reveals what people here consider respectable, fashionable, or worth complaining about.`;const marketItems=[[c.shop[0],2],[c.shop[1]||pick(e.artifacts),4],[c.shop[2]||'small luxury',6]];const entertainment=c.fun;const meals=c.food;const events=c.event;if(type==='social'){out.textContent=social;actions.innerHTML=e.people.slice(0,3).map((p,i)=>`<button data-social-person="${i}">Sit with the ${p}</button>`).join('');$$('[data-social-person]').forEach(b=>b.onclick=()=>talkToPerson(+b.dataset.socialPerson,'social'));}
if(type==='market'){out.innerHTML=`<b>Market near ${pick(e.places)}</b><br>You have ${walletGet()} local spending tokens for this visit. Prices are simplified for play, not historical currency conversion.`;actions.innerHTML=marketItems.map(([name,cost])=>`<button data-buy="${cost}" data-item="${name}">Buy ${name} • ${cost}</button>`).join('');$$('[data-buy]').forEach(b=>b.onclick=()=>{const cost=+b.dataset.buy;if(walletGet()<cost)return toast('Not enough spending tokens.');walletSet(walletGet()-cost);const buys=store.get('htp_purchases',[]);buys.push(`${e.title}: ${b.dataset.item}`);store.set('htp_purchases',buys);out.textContent=`You buy ${b.dataset.item}. The purchase gives you a small glimpse of what counts as necessity, status, or comfort in ${e.title}.`;});}
if(type==='entertainment'){const show=pick(entertainment);out.textContent=`Tonight's local option is ${show} near ${pick(e.places)}. The interesting part is not only the performance—it is who attends, how people behave, what it costs, and who may be excluded.`;actions.innerHTML=`<button data-town-act="attend">🎟️ Attend</button><button data-town-act="watch">👀 Watch the crowd</button><button data-town-act="leave">🌙 Take a quiet walk instead</button>`;}
if(type==='food'){out.textContent=`You choose ${pick(meals)} near ${pick(e.places)}. A ${pick(e.people)} points out which ingredients are common, what is seasonal, who prepared the meal, and how social status changes what appears on the table.`;actions.innerHTML=`<button data-town-act="share">Share a table</button><button data-town-act="kitchen">Ask how it was prepared</button><button data-town-act="budget">Compare a rich and modest meal</button>`;}
if(type==='calendar'){out.textContent=`Community calendar: ${pick(events)} is happening around ${pick(e.places)}. People are arranging work, clothes, travel, and social obligations around it.`;actions.innerHTML=`<button data-town-act="join">Join the event</button><button data-town-act="observe">Observe quietly</button><button data-town-act="volunteer">Help with preparations</button>`;}
if(type==='rumors'){const rumors=[`A ${pick(e.people)} says a visitor has been asking unusual questions near ${pick(e.places)}.`,`People are arguing about whether tomorrow's event will be canceled.`,`A package, letter, or delivery seems to have reached the wrong person.`];out.innerHTML=`<b>Three things people are saying:</b><br>1. ${rumors[0]}<br>2. ${rumors[1]}<br>3. ${rumors[2]}`;actions.innerHTML=`<button data-town-act="follow">Follow one rumor</button><button data-town-act="verify">Try to verify the story</button><button data-town-act="ignore">Ignore the gossip</button>`;}
$$('[data-town-act]').forEach(b=>b.onclick=()=>{out.textContent+=`

You choose to ${b.dataset.townAct}. ${pick(e.atmos)}. The moment becomes part of your continuing day.`;state.thread.push(`town life: ${b.dataset.townAct}`);store.set('htp_thread',state.thread);$('#journeyStatus').textContent=`${state.thread.length} connected moments in this visit.`});renderWallet()}


const livingCalendarData={
 titanic:{special:['A shipboard Sunday service is drawing passengers from several parts of the vessel.','A formal dinner has changed the rhythm of the evening promenade.','Passengers are gathering around posted notices and newly delivered messages.'],home:['Your cabin or shared room feels unusually still between public activities. Clothes must be brushed, belongings organized, and letters finished before the next meal.','A steward passes while you straighten a berth, fold a coat, and decide whether to write home or go upstairs for air.']},
 west:{special:['A livestock auction has pulled ranchers, traders, and curious townspeople onto Main Street.','A Saturday social is being prepared at the community hall.','A supply wagon arrived early, turning the general store into the busiest place in town.'],home:['A small household is preparing supper while boots, tools, and work clothes collect near the door.','Water must be carried, food prepared, lamps trimmed, and tomorrow’s chores discussed before anyone settles down.']},
 egypt:{special:['A market day has filled the river landing with sellers, boat crews, and household buyers.','A local religious observance is changing work schedules near the temple approach.','A boat convoy arrived with grain, pottery, cloth, and news from upriver.'],home:['In a shaded courtyard, bread, beer, linen, tools, and household work structure the day.','The hottest part of the day slows activity while family members repair clothing, prepare food, and sort supplies.']},
 medieval:{special:['Market day has crowded the square with carts, livestock, cloth, bread, and traveling sellers.','A feast-day procession is reshaping the village schedule.','A visiting performer has become the evening’s main attraction.'],home:['The household is centered around heat, food preparation, storage, mending, and work that rarely stops completely.','A small evening meal brings everyone together while tools are put away and tomorrow’s work is planned.']},
 victorian:{special:['A public lecture and exhibition have drawn a curious crowd near the gardens.','The theater district is unusually busy because a popular production opens tonight.','A charity fair has filled the arcade with stalls and decorated tables.'],home:['Coal must be managed, water heated, clothes brushed, correspondence answered, and meals timed around work.','A boarding-house sitting room becomes the center of quiet evening conversation, newspapers, sewing, and tea.']},
 fifties:{special:['A high-school game has turned the whole town toward the field.','A new movie opening has put a line around the block.','A downtown sales day has filled Main Street with music, signs, and shoppers.'],home:['The radio or television shapes the evening while supper, homework, phone calls, and household chores overlap.','A family kitchen becomes the busiest room as groceries are unpacked, plans are made, and neighbors drop in.']}
};
function calData(){const e=getEra(),d=livingCalendarData[state.era]||{};return {special:d.special||[`A busy market or public gathering has changed the rhythm around ${pick(e.places)}.`,`A seasonal community event has brought extra visitors to ${pick(e.places)}.`,`A local work cycle, observance, or public gathering is making today feel different.`],home:d.home||[`Inside an ordinary household, meals, cleaning, mending, storage, and work continue around the day’s public events.`,`A quieter domestic scene reveals how much daily life depends on routine, shared labor, and limited resources.`]}}
function relationshipInvite(){const rel=store.get('htp_rel',{}),cur=rel[state.era]||{},e=getEra();const known=Object.entries(cur).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]);const person=known.length?known[0][0]:pick(e.people);const n=known.length?known[0][1]:0;const where=pick(e.places);return n?`The ${person} you have spoken with ${n} time${n===1?'':'s'} has left word for you: meet them near ${where}. They have ${pick(['news to share','a small favor to ask','an invitation to a local gathering','something curious they think you should see'])}.`:`No one here knows you well enough to send a personal invitation yet, but a ${person} near ${where} seems open to conversation.`}
function returnPulse(){const key=`htp_last_${state.era}`,last=store.get(key,null),now=Date.now(),e=getEra();store.set(key,now);if(!last)return `This is your first recorded return check for ${e.title}. The portal marks today as the beginning of this era’s living timeline.`;const mins=Math.max(1,Math.round((now-last)/60000));const change=pick([`A familiar place near ${pick(e.places)} is busier than before.`,`Someone you met earlier has moved on to a new task near ${pick(e.places)}.`,`A local notice, rumor, or work schedule has changed since your last check.`,`The weather, crowd, and daily rhythm around ${pick(e.places)} feel different this time.`]);return `You were last here about ${mins} minute${mins===1?'':'s'} ago. ${change}`}
function livingCalendar(type){const e=getEra(),d=calData(),out=$('#calendarResult'),actions=$('#calendarActions');if(!out||!actions)return;actions.innerHTML='';if(type==='special'){out.textContent=`Special day in ${e.title}: ${pick(d.special)}`;actions.innerHTML=`<button data-cal-act="join">Join in</button><button data-cal-act="observe">Watch how people behave</button><button data-cal-act="help">Help with preparations</button>`}if(type==='home'){out.textContent=`Home & Hearth: ${pick(d.home)} A ${pick(e.people)} explains which chores, comforts, and worries are ordinary here.`;actions.innerHTML=`<button data-cal-act="meal">Help with the meal</button><button data-cal-act="chores">Take on a household chore</button><button data-cal-act="talk">Sit and talk with the household</button>`}if(type==='invite'){out.textContent=`Invitation check: ${relationshipInvite()}`;actions.innerHTML=`<button data-cal-act="accept">Accept the invitation</button><button data-cal-act="later">Save it for later</button><button data-cal-act="decline">Politely decline</button>`}if(type==='return'){out.textContent=`Return visit: ${returnPulse()}`;actions.innerHTML=`<button data-cal-act="investigate">See what changed</button><button data-cal-act="revisit">Visit a familiar place</button><button data-cal-act="newperson">Meet someone new</button>`}$$('[data-cal-act]').forEach(b=>b.onclick=()=>{const act=b.dataset.calAct;out.textContent+=`\n\nYou choose to ${act}. ${pick(e.atmos)}. The moment is added to your continuing journey.`;state.thread.push(`calendar: ${act}`);store.set('htp_thread',state.thread);$('#journeyStatus').textContent=`${state.thread.length} connected moments in this visit.`})}


const worldSystems={
  business(){
    const e=getEra(), place=pick(e.places), person=pick(e.people);
    const business=pick([`a small service operating near ${place}`,`a busy seller or workshop near ${place}`,`a locally important trade that depends on regular customers`,`a place where people come for repairs, supplies, food, lodging, or information`]);
    return `Businesses & Services — ${e.title}: You enter ${business}. A ${person} explains what people pay for, what must be ordered ahead, and which services everyone depends on.`;
  },
  economy(){
    const e=getEra(), need=pick(['food','fuel','rent or lodging','clothing repairs','transport','tools','schooling or training','medical help','household supplies']);
    const pressure=pick(['prices have risen','work has been irregular','something must be repaired instead of replaced','cash is limited so barter or credit matters','a seasonal expense has arrived']);
    return `Household Economy — ${e.title}: A household is trying to cover ${need}, but ${pressure}. You help decide what gets paid now, what can wait, and what can be made, borrowed, bartered, or repaired.`;
  },
  transport(){
    const e=getEra(), mode=pick(['walking','wagon or cart','horseback','boat or ship','rail','street transport','a hired ride','a crowded public route']);
    const snag=pick(['the route is slower than expected','weather changes the schedule','a crossing is delayed','space is limited','the road or path is rough','a connection has been missed']);
    return `Travel & Transport — ${e.title}: Your best available option is ${mode}. ${snag}. Reaching ${pick(e.places)} now takes planning instead of a simple click.`;
  },
  weather(){
    const e=getEra(), weather=pick(['heavy rain','thick fog','strong wind','sudden cold','oppressive heat','dusty conditions','a fast-moving storm','snow or sleet']);
    const effect=pick(['shops close early','travel slows down','workers change their routine','crowds move indoors','deliveries are delayed','a public event is altered','people begin sharing warnings and advice']);
    return `Weather Disruption — ${e.title}: ${weather} settles over the area and ${effect}. Your original plan changes with it.`;
  },
  chain(){
    const e=getEra();
    const a=pick(['a late delivery','a missing worker','a crowded market','a broken wheel','a rumor','a public announcement','a sudden weather change']);
    const b=pick(['forces a shop to improvise','changes who shows up at a gathering','sends someone looking for help','creates a shortage somewhere else','draws a crowd to a different part of town']);
    const c=pick(['a new opportunity appears','someone asks you to carry a message','a familiar person needs help','a mystery begins','your route through the day changes']);
    return `Event Chain — ${e.title}: First, ${a}. That ${b}. Before long, ${c}. One small event has now reshaped the rest of your visit.`;
  }
};
function worldSystem(type){
  const out=$('#worldSystemResult'), actions=$('#worldSystemActions'), e=getEra();
  if(!out||!actions||!worldSystems[type]) return;
  out.textContent=worldSystems[type]();
  actions.innerHTML=`<button data-world-act="enter">Follow it</button><button data-world-act="observe">Observe quietly</button><button data-world-act="ask">Ask a local</button><button data-world-act="adapt">Change your plan</button>`;
  $$('[data-world-act]').forEach(b=>b.onclick=()=>{
    const act=b.dataset.worldAct;
    const follow={enter:`You get involved and the situation pulls you toward ${pick(e.places)}.`,observe:`You stay out of the center and notice how ordinary people adjust around you.`,ask:`A ${pick(e.people)} gives you practical advice and a little local context.`,adapt:`You abandon the original plan and choose a route that fits the new conditions.`}[act];
    out.textContent += `

${follow} ${pick(e.atmos)}`;
    state.thread.push(`world system: ${type}/${act}`);
    store.set('htp_thread',state.thread);
    const s=$('#journeyStatus'); if(s) s.textContent=`${state.thread.length} connected moments in this visit.`;
  });
}


const backupKeys=()=>Object.keys(localStorage).filter(k=>k.startsWith('htp_'));
function backUpPortal(){
  const data={format:'HistoricalTimePortal',version:1,savedAt:new Date().toISOString(),items:{}};
  backupKeys().forEach(k=>{data.items[k]=localStorage.getItem(k)});
  const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});
  const url=URL.createObjectURL(blob),a=document.createElement('a');
  a.href=url;a.download='historical-time-portal-backup.json';document.body.append(a);a.click();a.remove();
  setTimeout(()=>URL.revokeObjectURL(url),1000);
  $('#backupStatus').textContent='Backup prepared. Keep the JSON file somewhere safe.';
}
async function restorePortal(file){
  if(!file)return;
  try{
    if(file.size>5_000_000)throw Error('The backup is too large.');
    const data=JSON.parse(await file.text());
    if(data?.format!=='HistoricalTimePortal'||data.version!==1||!data.items||typeof data.items!=='object'||Array.isArray(data.items))throw Error('This is not a compatible Portal backup.');
    const entries=Object.entries(data.items);
    if(entries.length>200||entries.some(([k,v])=>!/^htp_[a-zA-Z0-9_]+$/.test(k)||typeof v!=='string'||v.length>1_000_000))throw Error('This backup contains invalid data.');
    if(!confirm('Restore your Portal backup? This will replace your current Portal progress on this browser.'))return;
    backupKeys().forEach(k=>localStorage.removeItem(k));entries.forEach(([k,v])=>localStorage.setItem(k,v));
    $('#backupStatus').textContent='Backup restored. Refreshing your adventures…';location.reload();
  }catch(e){ $('#backupStatus').textContent='Could not restore: '+e.message }
}

function wire(){
 $('#saveBackupBtn').onclick=backUpPortal;$('#loadBackupBtn').onclick=()=>$('#backupFile').click();$('#backupFile').onchange=e=>restorePortal(e.target.files[0]);
 $$('[data-calendar]').forEach(b=>b.onclick=()=>livingCalendar(b.dataset.calendar));$$('[data-worldsys]').forEach(b=>b.onclick=()=>worldSystem(b.dataset.worldsys));
 $$('[data-era]').forEach(b=>b.onclick=()=>openEra(b.dataset.era));$$('.mode-card').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
 $('#todayBtn').onclick=event;$('#rerollEvent').onclick=event;$('#surpriseBtn').onclick=randomAdventure;$('#fullRandomBtn').onclick=randomAdventure;$('#newSceneBtn').onclick=()=>renderEra();$('#roleBtn').onclick=()=>{$('#role').textContent=pick(getEra().roles)};$('#daypartBtn').onclick=atmosphereAdvance;$('#customBtn').onclick=()=>{const v=$('#customInput').value.trim();if(v){doChoice(v);$('#customInput').value=''}};$('#customInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#customBtn').click()});
 $$('.life-card').forEach(b=>b.onclick=()=>life(b.dataset.life));$('#newCaseBtn').onclick=newCase;$('#clueBtn').onclick=addClue;$('#witnessBtn').onclick=witness;$('#solveCaseBtn').onclick=solve;$$('.game-btn').forEach(b=>b.onclick=()=>playGame(b.dataset.game));$('#resetScore').onclick=()=>{state.score=state.questions=0;$('#score').textContent=$('#questions').textContent='0';$('#gamePanel').textContent='Score reset. Choose a game.';gameLocked=false};
 $$('.mini-card').forEach(b=>b.onclick=()=>mini(b.dataset.mini));$$('[data-titanic]').forEach(b=>b.onclick=()=>titanic(b.dataset.titanic));$$('[data-townlife]').forEach(b=>b.onclick=()=>townLife(b.dataset.townlife));$('#resetWalletBtn').onclick=()=>{walletSet(12);$('#townLifeResult').textContent='Visit money reset to 12 local spending tokens.';$('#townLifeActions').innerHTML=''};
 $('#savePersonaBtn').onclick=savePersona;$('#loadPersonaBtn').onclick=loadPersona;$('#rerollPersonaBtn').onclick=rerollPersona;$('#startStoryBtn').onclick=storyStart;$('#nextStoryBtn').onclick=()=>storyNext(false);$('#branchStoryBtn').onclick=()=>storyNext(true);$('#endStoryBtn').onclick=storyEnd;$('#refreshDeckBtn').onclick=renderDeck;$('#buildRouteBtn').onclick=buildRoute;$('#walkRouteBtn').onclick=walkRoute;
 $('#journalSave').onclick=()=>{const v=$('#journalInput').value.trim();if(!v)return;const j=store.get('htp_journal',[]);j.push({era:getEra().title,text:v});store.set('htp_journal',j);$('#journalInput').value='';renderJournal();renderAchievements()};
 $('#discoverBtn').onclick=()=>{const a=pick(getEra().artifacts),arr=store.get('htp_artifacts',[]);arr.push(`${getEra().title}: ${a}`);store.set('htp_artifacts',arr);renderCollections();renderAchievements();toast(`Discovered: ${a}`)};$('#favoriteBtn').onclick=()=>{const a=store.get('htp_favs',[]);if(!a.includes(state.era))a.push(state.era);store.set('htp_favs',a);renderCollections()};
 $$('[data-companion]').forEach(b=>b.onclick=()=>{$('#companionResult').textContent=`${b.querySelector('b').textContent} is traveling with you. ${pick(['Expect more context and historical detail.','Expect clues and inconsistencies to be highlighted.','Expect local food, places, and people to be suggested.','Expect ordinary moments to become stronger story hooks.'])}`});
 $('#planDayBtn').onclick=planDay;$('#saveMomentBtn').onclick=()=>{const m=store.get('htp_memories',[]);m.push({era:getEra().title,scene:$('#sceneText').textContent});store.set('htp_memories',m);renderMemories()};$('#memorySurpriseBtn').onclick=()=>{const m=store.get('htp_memories',[]);if(m.length){const x=pick(m);$('#sceneText').textContent=`Memory from ${x.era}: ${x.scene}`;$('#experiencePanel').scrollIntoView({behavior:'smooth'})}};$('#visitMixerBtn').onclick=mixVisit;$('#continueJourneyBtn').onclick=continueDay;$('#freshThreadBtn').onclick=freshThread;$('#clearRelations').onclick=()=>{const r=store.get('htp_rel',{});delete r[state.era];store.set('htp_rel',r);renderRelations()};
 $('#chronicleStartBtn').onclick=chronicleStart;$('#chronicleNextBtn').onclick=chronicleNext;$('#chronicleSaveBtn').onclick=chronicleSave;$('#noticeBtn').onclick=noticeSomething;$('#clearNoticesBtn').onclick=()=>{store.set('htp_notices',[]);renderNotices()};
 $$('.mood-btn').forEach(b=>b.onclick=()=>{const map={relax:'cozy',curious:'explore',social:'roleplay',dramatic:'story',challenge:'games',surprise:pick(Object.keys(modes))};setMode(map[b.dataset.mood]);$('#moodResult').textContent=`Mood set: ${b.textContent.trim()}. The current portal has been reshaped around that choice.`});
 $$('.episode-card').forEach(b=>b.onclick=()=>{const n=b.querySelector('b').textContent;state.mode=b.dataset.episode==='mystery'?'mystery':b.dataset.episode==='quiet'?'cozy':'story';renderEra();$('#sceneText').textContent=`Portal Theater — ${n}: ${sceneFor(state.mode)}`;$('#experiencePanel').scrollIntoView({behavior:'smooth'})});
 }
 function init(){document.body.dataset.era='titanic';state.thread=store.get('htp_thread',[]);state.era=eras[store.get('htp_last_era','titanic')]?store.get('htp_last_era','titanic'):'titanic';state.mode=modes[store.get('htp_last_mode','roleplay')]?store.get('htp_last_mode','roleplay'):'roleplay';state.persona=store.get(`htp_persona_${state.era}`,null);wire();$$('.mode-card').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));renderEra();renderWallet();renderPassport();renderJournal();renderCollections();renderQuests();renderAchievements();renderRelations();renderMemories();renderChronicleLibrary();renderNotices();event();buildRoute();window.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.activeElement instanceof HTMLElement)document.activeElement.blur()})}
 document.addEventListener('DOMContentLoaded',init);
})();
